config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create, :new, :destroy, :show]
  resources :articles, only: [:create, :destroy, :new, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :show]
  
  def show
    @article = Article.find(params[:id])

  end
  
  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    
    if @article.save
      flash[:success] = '投稿しました。'
      redirect_to @article
    else
      flash.now[:danger] = "投稿できませんでした"
      render :new
    end
    
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update(article_params)
      flash[:success] = '変更しました。'
      redirect_to @article
    else
      flash.now[:danger] = '変更できませんでした。'
      render :edit
    end
    
  end

  def destroy
    @user = current_user
    
    @article.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to @user
  end
  
  private
  
  def article_params
    params.require(:article).permit(:comment, :title, :code)
  end
  
  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    unless @article
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = current_user
    
    if logged_in?
      redirect_to @user
    end
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      redirect_back(fallback_location: root_path) 
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @user = current_user
    
    if logged_in?
      redirect_to @user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_user_logged_in, only: [:index, :show, :destroy]
  
  def show
    @user = User.find(params[:id])
    @articles = current_user.articles.order('created_at DESC').page(params[:page]).per(10)
    
    unless current_user == @user
      redirect_to root_path
    end
  end

  def new
    @user = User.new
    @userpage = current_user
    
    if logged_in?
      flash[:notice] = "ログインしています。"
      redirect_to @userpage
    end
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザー登録が完了しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/articles/edit.html.erb
    <div id="maindiv">

        <div id="articles_newedit">
          
          <%= form_for(@article) do |f| %>
            <div>
              <%= f.label :title, 'Title' %>
              <%= f.text_field :title, class: 'txt' %>
            </div>
            
            <div>
              <%= f.label :code, 'Code' %>
              <%= f.text_area :code, rows: 40, class: 'txt' %>
            </div>
            
            <div>
              <%= f.label :comment, 'Comment' %>
              <%= f.text_area :comment, rows: 40, class: 'txt' %>
            </div>
            
            <%= f.submit '変更', class: 'submit' %>
          <% end %>

        </div>
    </div>

app/views/articles/new.html.erb
    <div id="maindiv">

        <div id="articles_newedit">
          
          <%= form_for(@article) do |f| %>
            <div>
              <%= f.label :title, 'Title' %>
              <%= f.text_field :title, class: 'txt' %>
            </div>
            
            <div>
              <%= f.label :code, 'Code' %>
              <%= f.text_area :code, rows: 40, class: 'txt' %>
            </div>
            
            <div>
              <%= f.label :comment, 'Comment' %>
              <%= f.text_area :comment, rows: 40, class: 'txt' %>
            </div>
            
            <%= f.submit '登録', class: 'submit' %>
          <% end %>

        </div>
    </div>

app/views/articles/show.html.erb
    <div id="maindiv">

        <articel id="articles_show">
            <h2><%= @article.title %></h2>
            <secttion>
                <h3>Code</h3>
                <pre><%= @article.code %></pre>
            </secttion>

            <secttion>
                <h3>Comment</h3>
                <p class="article_comment"><%= @article.comment %></p>
                <p class="destroy_btn"><%= link_to "削除", @article, method: :delete, data: { confirm: "削除してよろしいですか？" } %></p>
            </secttion>
        </articel>

        <div id="iconlink">
            <ul>
                <li>
                    <a class="svgicon" href="<%= user_path(current_user) %>">
                        <svg class="icon">
                            <use xlink:href="#icon-undo2" />
                        </svg>
                    </a>
                    <p><%= link_to '一覧', user_path(current_user) %></p>
                </li>
                <li>
                    <a class="svgicon" href="<%= edit_article_path %>">
                        <svg class="icon">
                            <use xlink:href="#icon-quill" />
                        </svg>
                    </a>
                    <p><%= link_to '編集', edit_article_path %></p>
                </li>
            </ul>
        </div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert_<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
    <header>
        <% if logged_in? %>
            <h1><i><%= link_to 'Codememo', user_path(current_user), id: 'logo' %></i></h1>
        <% else %>
            <h1><i><%= link_to 'Codememo', root_path, id: 'logo' %></i></h1>
        <% end %>
        <ul>
            <% if logged_in? %>
              <li><%= link_to current_user.name + 'さん', user_path(current_user) %></li>
              <li><%= link_to 'Logout', logout_path, method: :delete, class: 'header_btn' %></li>
            <% else %>
            <% if request.path == "/" %>
                <li><%= link_to 'Signup', signup_path, class: 'header_btn' %></li>
            <% else %>
                <li><%= link_to 'Login', root_path, class: 'header_btn' %></li>
            <% end %>
            <% end %>
            
        </ul>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <% case request.fullpath
        when '/', 'toppages/index', 'signup', 'users/new' %>
        <meta name="description" content="個人的なコードメモ・すぐに忘れるのでメモ帳にメモするみたいに使えるプライベートなコードメモです">
    <% else %>
        <meta name="robots" content="noindex">
    <% end %>
    <title>Codememos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller_name %><%= action_name %>">
    <svg style="display:none;" class="svg">
        <defs>
            <symbol id="icon-quill" viewBox="0 0 32 32">
                <title>quill</title>
                <path d="M0 32c4-12 14.469-32 32-32-8.219 6.594-12 22-18 22s-6 0-6 0l-6 10h-2z"></path>
            </symbol>
            <symbol id="icon-undo2" viewBox="0 0 32 32">
                <title>undo2</title>
                <path d="M23.808 32c3.554-6.439 4.153-16.26-9.808-15.932v7.932l-12-12 12-12v7.762c16.718-0.436 18.58 14.757 9.808 24.238z"></path>
            </symbol>
            <symbol id="icon-plus" viewBox="0 0 32 32">
                <title>plus</title>
                <path d="M31 12h-11v-11c0-0.552-0.448-1-1-1h-6c-0.552 0-1 0.448-1 1v11h-11c-0.552 0-1 0.448-1 1v6c0 0.552 0.448 1 1 1h11v11c0 0.552 0.448 1 1 1h6c0.552 0 1-0.448 1-1v-11h11c0.552 0 1-0.448 1-1v-6c0-0.552-0.448-1-1-1z"></path>
            </symbol>
        </defs>
    </svg>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/toppages/index.html.erb
    <div id="login_signup">
        
        <%= form_for(:session, url: login_path) do |f| %>
        
          <div>
            <%= f.label :email, 'e-mail' %>
            <%= f.email_field :email, class: 'txt' %>
          </div>
          
          <div>
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'txt' %>
          </div>
          
          <%= f.submit 'Login', class: 'submit' %>
        
        <% end %>
        
    </div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
    <div id="login_signup">
      
        <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div>
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'txt' %>
          </div>
          
          <div>
            <%= f.label :email, 'e-mail' %>
            <%= f.email_field :email, class: 'txt' %>
          </div>
          
          <div>
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'txt' %>
          </div>
          
          <div>
            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation, class: 'txt' %>
          </div>
          
          <%= f.submit 'Sign up', class: 'submit' %>
        <% end %>
      
    </div>

app/views/users/show.html.erb
    <div id="maindiv">
        
        <% @articles.each do |article| %>

        <a class="user_box_link" href="<%= article_path(article) %>">
            <article class="user_box">
                <h2><%= article.title %></h2>
                <p><%= article.comment.truncate(100, omission: '...') %></p>
            </article>
        </a>
        
        <% end %>
        
        <%= paginate @articles %>

    </div>

    <div id="iconlink">
        <a class="svgicon" href="<%= new_article_path %>">
            <svg class="icon">
                <use xlink:href="#icon-plus" />
            </svg>
        </a>
        <p><%= link_to '登録', new_article_path %></link_to></p>
    </div>